### ISSUE TITLE
"@tailus/themer" has no exported member named Palette

### ISSUE THREAD

**Issue by Sw0xy** [Tailus-UI/themer#11]
**Describe the bug**
I copied the theme switcher components from [here](https://ui.tailus.io/themer/theming/palette/) it seems it doesn't work.
**To Reproduce**
1. install @tailus/themer
2. import palettesArray, type Palette from "@tailus/themer" according to [docs](https://ui.tailus.io/themer/theming/palette/)

**Expected behavior**
Be able to import `palettesArray` and ` type Palette`

**Screenshots**
![image](https://github.com/Tailus-UI/themer/assets/58565946/12c79d2f-1f22-4cf4-9298-68c6099eb869)

**Desktop (please complete the following information):**
 - OS:  Ubuntu 
 - Browser: chromium
 - Version: 125.0.6422.141

**Comment by Meschacirung** [comment]
Fixed :

- Install the latest  Tailus Themer  and Themer Plugins : ``npm i @tailus/themer@latest @tailus/themer-plugins@latest``
- I also updated the [theme switcher ](https://ui.tailus.io/react/theming/palette/#theme-switcher) code
